load("//graph/schema:schema.bzl", "create_full_schema")

create_full_schema(
    name = "all",
    deps = [
        "//graph/schema/definition:source",
        "//graph/schema/definition/language:glotto_language",
        "//graph/schema/definition/dictionary:chinese_dictionary_entry",
        "//graph/schema/definition/dictionary:chinese_dictionary_entry_definition",
    ]
)