package_group(
    name = "schema",
    packages = [
        "//graph/schema/...",
        "//graph/create/...",
    ]
)

package_group(
    name = "create",
    packages = [
        "//graph/create/...",
    ]
)